// <auto-generated />
namespace MAFS_ReStart.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class YouTubeLink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YouTubeLink));
        
        string IMigrationMetadata.Id
        {
            get { return "201804042300587_YouTubeLink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
